cc_test(
    name = "query_test",
    srcs = ["query_unittest.cpp"],
    deps = [
        "//:query",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "roaring_test",
    srcs = ["roaring_unittest.cpp"],
    deps = [
        "@com_github_croaring//:roaring",
        "@com_github_croaring//:roaring-cpp",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
