cc_test(
    name = "query_test",
    srcs = ["query_unittest.cpp"],
    deps = [
        "//:query",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
